
string(ASCII 27 Esc)
if(WIN32)
  set(Reset "${Esc}[0m")
else()
  set(Reset "${Esc}[m")
endif()

set(Bold        "${Esc}[1m")
set(Red         "${Esc}[31m")
set(Green       "${Esc}[32m")
set(Yellow      "${Esc}[33m")
set(Blue        "${Esc}[34m")
set(Magenta     "${Esc}[35m")
set(Cyan        "${Esc}[36m")
set(White       "${Esc}[37m")
set(BoldRed     "${Esc}[1;31m")
set(BoldGreen   "${Esc}[1;32m")
set(BoldYellow  "${Esc}[1;33m")
set(BoldBlue    "${Esc}[1;34m")
set(BoldMagenta "${Esc}[1;35m")
set(BoldCyan    "${Esc}[1;36m")
set(BoldWhite   "${Esc}[1;37m")


set(COLOR_LIST Bold Red Green Yellow Blue Magenta Cyan White BoldRed BoldGreen BoldYellow BoldBlue BoldMagenta BoldCyan BoldWhite)



function(message)
  list(GET ARGV 0 MessageType)
  list(FIND COLOR_LIST ${MessageType} INDEX)
  if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${BoldRed}${ARGV}${Reset}")
  elseif(MessageType STREQUAL WARNING)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${Yellow}${ARGV}${Reset}")
  elseif(MessageType STREQUAL AUTHOR_WARNING)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${Magenta}${ARGV}${Reset}")
  elseif(MessageType STREQUAL STATUS)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${Cyan}${ARGV}${Reset}")
  elseif(INDEX)
    list(GET COLOR_LIST ${INDEX} COLOR_NAME)
    set(COLOR ${${COLOR_NAME}})
    list(REMOVE_AT ARGV 0)
    _message(STATUS "${COLOR}${ARGV}${Reset}")
  else()
    _message("${ARGV}${Reset}")
  endif()
endfunction()